apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-app
  namespace: sample-app
  labels:
    app: sample-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-node-app
  template:
    metadata:
      labels:
        app: sample-node-app
    spec:
      containers:
      - name: sample-node-app
        image: sample-node-app:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: ELASTIC_APM_SERVER_URL
          value: "http://apm-server-apm-http.logging.svc.cluster.local:8200"
        - name: ELASTIC_APM_SERVICE_NAME
          value: "sample-node-app"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sample-node-app
  namespace: sample-app
  labels:
    app: sample-node-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app: sample-node-app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-node-app
  namespace: sample-app
  labels:
    team: devops
spec:
  selector:
    matchLabels:
      app: sample-node-app
  endpoints:
  - port: http
    path: /metrics
